### ISSUE TITLE
Error during trimming alignments while running test dataset

### ISSUE THREAD

**Issue by Jimaz** [fethalen/Patchwork#45]
Hi! First of all, congrats for this great tool, it's awsome. After struggling with the compilation problems with the Biosequences update, I'm trying to run the tool without compiling but I get this error in the trimming step:

`$ julia src/Patchwork.jl --contigs test/07673_dna.fa --reference test/07673_Alitta_succinea.fa --threads 1`

````
P A T C H W O R K
- Developers: Felix Thalén & Clara G. Köhne         - Cite      : In prep.
- Contact   : <felix.thalen@uni-goettingen.de>      - DIAMOND v.: 2.0.15
- Wiki      : github.com/fethalen/patchwork/wiki    - Threads   : 1
──────────────────────────────────────────────────────────────────────────
Building DIAMOND database...
Aligning query sequences against reference database...
Merging overlapping hits...
Trimming alignments...
ERROR: MethodError: no method matching Main.Patchwork.SequenceRecord(::StringViews.StringView{SubArray{UInt8, 1, Vector{UInt8}, Tuple{UnitRange{Int64}}, true}}, ::StringViews.StringView{SubArray{UInt8, 1, Vector{UInt8}, Tuple{UnitRange{Int64}}, true}})
Closest candidates are:
  Main.Patchwork.SequenceRecord(::AbstractString) at ~/SOFT/patchwork/src/sequencerecord.jl:19
  Main.Patchwork.SequenceRecord(::AbstractString, ::BioSequences.LongSequence) at ~/SOFT/patchwork/src/sequencerecord.jl:27
Stacktrace:
  [1] (::Main.Patchwork.var"#76#77"{Main.Patchwork.SequenceIdentifier, FASTX.FASTA.Record})(reader::FASTX.FASTA.Reader{TranscodingStreams.NoopStream{IOStream}})
    @ Main.Patchwork ~/SOFT/patchwork/src/fasta.jl:144
  [2] open(f::Main.Patchwork.var"#76#77"{Main.Patchwork.SequenceIdentifier, FASTX.FASTA.Record}, ::Type{FASTX.FASTA.Reader}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ BioGenerics.IO ~/SOFT/miniconda3/envs/patchwork/share/julia/packages/BioGenerics/1d69j/src/IO.jl:57
  [3] open
    @ ~/SOFT/miniconda3/envs/patchwork/share/julia/packages/BioGenerics/1d69j/src/IO.jl:54 [inlined]
  [4] selectsequence(fastafile::String, identifier::Main.Patchwork.SequenceIdentifier)
    @ Main.Patchwork ~/SOFT/patchwork/src/fasta.jl:139
  [5] main()
    @ Main.Patchwork ~/SOFT/patchwork/src/Patchwork.jl:401
  [6] julia_main()
    @ Main.Patchwork ~/SOFT/patchwork/src/Patchwork.jl:461
  [7] top-level scope
    @ ~/SOFT/patchwork/src/Patchwork.jl:471
  [8] include(mod::Module, _path::String)
    @ Base ./Base.jl:419
  [9] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:303
 [10] _start()
    @ Base ./client.jl:522
```
I have no clue what is going on as I'm not expertise in Julia language. Thanks in advance. 

Cheers, 

Jaime

**Comment by ClaraKoehne** [comment]
Hello! Thanks for the nice words, and thanks for the info. The main branch is currently out of order, but I'm working on it. There were some updates to Julia, we're now using a new version (1.8.2), and not all the files and dependencies have been updated correctly on the main branch. I'll notify you once it's done, shouldn't be too long now.
Best, 
Clara

**Comment by ClaraKoehne** [comment]
Good morning. I took care of the problem; Patchwork should run correctly again now. If you don't mind, I'd close the issue now. Please do say if there's something else that doesn't work!
Best, 
Clara
P.S.: There's just a small something I noticed in your julia command above: If you run Patchwork without compiling (as I would recommend, because the compiled program is so large), I'd recommend you include the `--project` option in your julia calls: (from inside the Patchwork directory) do `julia --project=. -e "import Pkg; Pkg.instantiate()` (only required once, after downloading the code for Patchwork) and call Patchwork like `julia --project=. src/Patchwork.jl`. By instantiating, you can make sure that all dependencies are downloaded and available when you start the program. Running Patchwork will also work without instantiating and without the `--project` option, but then you might have to install the dependencies (julia packages) manually first. (See further instructions in our GitHub Wiki)
