### ISSUE TITLE
Error during installation: Conda fails to resolve dependencies

### ISSUE THREAD

**Issue by mptrsen** [fethalen/Patchwork#46]
Installation with dependencies from Conda according to [the instructions](https://github.com/fethalen/Patchwork/wiki/4.-Installation#run-patchwork-without-compiling) fails at the `Pkg.instantiate()` step. [Long error output here.](https://gist.github.com/mptrsen/a8ea61b7fe28c166a10a2a5682a6d493) Perhaps the issue is that the distutils package is deprecated and the submodule sysconfig wasn't found:

```
$ mamba create -p conda/patchwork -c bioconda -c conda-forge diamond julia
$ mamba activate conda/patchwork/
$ git clone https://github.com/fethalen/patchwork
$ cd patchwork/
$ julia --project=. -e 'import Pkg; Pkg.instantiate()'
[...long list of dependencies being downloaded...]
ERROR: Error building `PyCall`: 
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils.sysconfig'
[...]
```

**Comment by ClaraKoehne** [comment]
Hello! I can't reproduce the error on my system. But in the long error output, it seems like you have no system-wide python installation? I'm not sure how to solve this. However, it seems like something else is broken in the conda installation of julia anyways; for the latest julia version (1.8.2), I am missing some certificate files when installing with conda. The alternative would be to not use a conda environment but instead download julia and diamond like so:
```
wget https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.2-linux-x86_64.tar.gz
tar -xzf julia-1.8.2-linux-x86_64.tar.gz
```
(julia version 1.8.2 for Linux)
```
wget http://github.com/bbuchfink/diamond/releases/download/v2.0.13/diamond-linux64.tar.gz
tar xzf diamond-linux64.tar.gz
```
(diamond version 2.0.13 for Linux)
Make sure that both programs are in your `$PATH` variable so that you can call them from the terminal. I should add that Patchwork's main branch might be broken right now, but that's an issue I'm currently solving.

**Comment by ClaraKoehne** [comment]
The main branch should work again now, just so you know.
